### ISSUE TITLE
several missing in documentation

### ISSUE THREAD

**Issue by rcemper** [caretdev/iris-python-faker#2]
- what is the purpose of the 'faker'  and what is faked?
- a guide of how to navigate through the  tool 
- a practical working example and how to verfiy the result
-  what licensing is required for the generated data.
-
- a personal question: 
In which way is this better than POPULATE      
that I use for ages with much more flexibility

**Comment by daimor** [comment]
> what is the purpose of the 'faker' and what is faked?  

reasonable, I'll add it

> a guide of how to navigate through the tool

I'll update, to give more info

> a practical working example and how to verfiy the result

Not, sure, what has to be verified, it's generated data. The project contains some UnitTests, which check some of the cases.

> what licensing is required for the generated data.
fake data does not require any licenses

> In which way is this better than POPULATE

Link to [documentation](https://faker.readthedocs.io/en/master/fakerclass.html) of that Python faker library
And in fact, there are many other implementations of faker-like libraries for other languages.

POPULATE are just so much far from any of Faker implementations. Populate can just generate some random string or some random numbers. With faker
- Data close to reality, names, addresses, and so on, just looks very similar to real, not as just a branch of letters
- Data can be localized, so, that data can be Austrian specific, or in Russian, or even in Chinese, lots of localizations available
- Randomizer here based on dictionaries, such as FirstNames, Countries, and so on.
- it even can generate some text, with no sense for sure, like lorem ipsum, but with real words.
- Original library, has much more options than I've implemented, more providers you can find by link https://faker.readthedocs.io/en/master/providers.html

**Comment by rcemper** [comment]
Thanks for the clarification.
The 5 point section at the end is an excellent reasoning for using it.  (even with mentioning POPULATE)
Especially the localization is a strong selling point.  You should really push on it! to wake people.
I assume the majority of our audience knows the pain with Populate and the limits. 
But you should wake them up like me.
